/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.ProductoJpaController;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;

/**
 *
 * @author matias
 */
public class products_table extends javax.swing.JFrame {
    ProductoJpaController productoController; 
    /**
     * Creates new form products_table
     */
    public products_table() {
        initComponents();
        this.productoController = new ProductoJpaController();
        mostrar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbprod = new javax.swing.JTable();
        btnmostrar = new javax.swing.JButton();
        txtprod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbltotalregistros = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbprod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbprodMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbprod);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 69, 546, 107));

        btnmostrar.setBackground(new java.awt.Color(51, 102, 255));
        btnmostrar.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        btnmostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnmostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen4.png"))); // NOI18N
        btnmostrar.setText("Mostrar todo");
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 6, -1, -1));

        txtprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprodKeyReleased(evt);
            }
        });
        jPanel1.add(txtprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 17, 135, 22));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BUSCAR PRODUCTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        lbltotalregistros.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbltotalregistros.setForeground(new java.awt.Color(255, 255, 255));
        lbltotalregistros.setText("jLabel3");
        jPanel1.add(lbltotalregistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 206, 64, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Registros:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 208, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void mostrar(String buscar)  {
         try {
         String[] titulos = {"Codigo","Nombre", "Marca", "Modelo", "Precio", "Cantidad"};
         DefaultTableModel modelo = new DefaultTableModel(null, titulos);
            List<Producto> products = productoController.search(buscar);
             String[] productos = new String[6];
             products.forEach((product) -> {
                    productos[0] = product.getId().toString();
                 productos[1] = product.getNombre();
                 productos[2] = product.getMarcaId().getDescripcion();
                 productos[3] = product.getModelo();
                 productos[4] = product.getPrecio().toString();
                 productos[5] = product.getCantidad().toString();
                
                 modelo.addRow(productos);
             });
             
             tbprod.setModel(modelo);
             lbltotalregistros.setText("Total Registros: "+Integer.toString(productoController.getProductoCount()));
         } catch (Exception e) {
              JOptionPane.showMessageDialog(rootPane, "error al cargar tabla de clientes");
              System.out.println("products_table::mostrar | error = " + e.getMessage());
              e.getStackTrace();
         }
    }
    
    private void tbprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbprodMouseClicked
        // TODO add your handling code here:
        try {

            DefaultTableModel tabladet = (DefaultTableModel) inicio.tbdet.getModel();
            String[]  dato=new String[5];

            int  fila = tbprod.getSelectedRow();
            System.out.println("fila = " + fila);
            if(fila==-1)
            {
                JOptionPane.showMessageDialog(null, "No  ha seleccionado ningun registro");
            }

            else
            {
                String codins=tbprod.getValueAt(fila, 0).toString();
                String desins=tbprod.getValueAt(fila, 1).toString() + " " + tbprod.getValueAt(fila, 3).toString();
                String cantins=tbprod.getValueAt(fila,5).toString();
                String preins=tbprod.getValueAt(fila, 4).toString();
                int c=0;
                int j=0;
                String  cant=JOptionPane.showInputDialog("ingrese cantidad");
                if((cant == null) || (cant.equals("")) || (cant.equals("0")))
                {
                    JOptionPane.showMessageDialog(this, "Debe ingresar algun valor mayor que 0");
                }
                else
                {

                    int canting=Integer.parseInt(cant);
                    int comp=Integer.parseInt(cantins);
                    if(canting>comp)
                    {
                        JOptionPane.showMessageDialog(this,"Ud. no cuenta con el stock apropiado");
                    }
                    else
                    {
                        for(int i=0;i < inicio.tbdet.getRowCount(); i++)
                        {
                            Object com=inicio.tbdet.getValueAt(i,0);
                            System.out.println("com = " + com);
                            if(codins.equals(com))
                            {
                                j=i;
                                inicio.tbdet.setValueAt(cant, i, 3);
                                c=c+1;

                            }

                        }
                        if(c==0)
                        {

                            dato[0]=codins;
                            dato[1]=desins;
                            dato[2]=preins;
                            dato[3]=cant;

                            tabladet.addRow(dato);

                            inicio.tbdet.setModel(tabladet);

                        }
                    }

                }

            }
               this.dispose();
        } catch (HeadlessException  | NumberFormatException e) {
            System.out.println("produtcs_table::mouseclicked | error = " + e.getMessage());
            e.getStackTrace();
        }
    }//GEN-LAST:event_tbprodMouseClicked

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
        // TODO add your handling code here:
        mostrar("");
    }//GEN-LAST:event_btnmostrarActionPerformed

    private void txtprodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprodKeyReleased
        // TODO add your handling code here:
        mostrar(txtprod.getText());
    }//GEN-LAST:event_txtprodKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(products_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(products_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(products_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(products_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new products_table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbltotalregistros;
    private javax.swing.JTable tbprod;
    private javax.swing.JTextField txtprod;
    // End of variables declaration//GEN-END:variables
}
